### ISSUE TITLE
[Backend] Identify why the explorer is not working and correct it

### ISSUE THREAD

**Issue by rafaeldkb** [hack-a-chain-software/indexer-kadena#85]
@davibauer this is the most urgent task. Our explorer is barely working. It takes a long time to open homescreen. When clicking in any of the other pages (Transactions/Blocks/Tokens) it usually doesnt open and show this error: 

![Image](https://github.com/user-attachments/assets/51be39bc-4d3c-41d0-a93f-6d574de63281)

- [ ] Analyze issues
- [ ] Make sure we have the explorer running, so we can thoroughly test it with all the other features

**Comment by davibauer** [comment]
@rafaeldkb Estou tendo esse problema no streaming, tu lembra de ter alterado alguma chave na AWS? 

Parace que as credenciais que estávamos usando para acesso ao S3 não existe mais, começou a ocorrer desde ontem.

> Error listing S3 objects: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

Sobre o GraphQL, eu subi uma atualização para ele apontar para a réplica de leitura que criei. Também subi as alterações no github.

**Comment by davibauer** [comment]
Kadscan está no ar

![Image](https://github.com/user-attachments/assets/3ebfc0aa-597b-4771-b518-590c16b2ee36)

**Comment by davibauer** [comment]
Vai perceber que os blocos que aparecem são apenas até ontem, por conta dessa questão da chave da AWS.

**Comment by davibauer** [comment]
Eu troquei a chave, e agora está funcionando novamente o streaming.

![Image](https://github.com/user-attachments/assets/742886dc-d4c1-498a-8a8a-f36d8ddcfa76)

**Comment by bernardonery** [comment]
@rafaeldkb 
@davibauer Eu coloquei aqui uns prints de uma sequência de transações que aparecem que estão em um mesmo timestamp. Achei bem estranho devido ao volume de transações feitas. Vai da página 2 até a 46. Depois tem uma outra sequencia estranha. Isso se dá ao Backfil de ter ficado fora do ar ou algo mais momentâneo. 
Não lembro de ter visto um volume tão grande assim na rede deles. 

![Image](https://github.com/user-attachments/assets/6473fd4d-3fc1-46a7-87ed-44317e0ff175)



![Image](https://github.com/user-attachments/assets/1e5b408f-cb40-47dc-9d30-d05ce79123c0)



![Image](https://github.com/user-attachments/assets/90af69ba-6f6b-44fe-8468-362bf89ed6f9)

**Comment by rafaeldkb** [comment]
> Member

Esses timestamps tão estranhos mesmo. Tem que criar uma issue pra entender de onde tão vindo os timestamps e fazer uma verificação se isso tá certo. Cria uma issue separada e coloca no backlog. Essa é de front, pro Mat.
