### ISSUE TITLE
[Footer] Change footer text

### ISSUE THREAD

**Issue by rafaeldkb** [hack-a-chain-software/indexer-kadena#86]
@1Mateus 

Change the footer text.

Current: Kadscan is the leading blockchain explorer dedicated to the Kadena ecosystem. Powered by Kadena Protocol.

New one: Kadscan is the leading blockchain explorer dedicated to the Kadena ecosystem. Powered by Hack-a-Chain. 

Also, add our logo (Hack-a-Chain).

![Image](https://github.com/user-attachments/assets/609e9c7b-fcf1-4403-b11a-0148379dfe45)

**Comment by bernardonery** [comment]
@rafaeldkb It's Done:


![Image](https://github.com/user-attachments/assets/e6c56798-6059-43a5-afc9-db0577f0b114)
