### ISSUE TITLE
[Homescreen] Price history

### ISSUE THREAD

**Issue by rafaeldkb** [hack-a-chain-software/indexer-kadena#87]
This graph with price history has the wrong title, it's not "Total transactions history in 14 days", it's "KDA Price 14 days". Is it possible to add the possibility of filtering the price by date? Like, day, week, month, year, and custom? @1Mateus 

I just realized how shity it is right now. 

![Image](https://github.com/user-attachments/assets/ad197ddd-2642-4567-ad94-d0f634b1ab28)

**Comment by bernardonery** [comment]
It's done:


![Image](https://github.com/user-attachments/assets/1fa42a2d-446e-4690-ab2f-d7453d753132)
