### ISSUE TITLE
[Homescreen] Add "Total volume 24h"

### ISSUE THREAD

**Issue by rafaeldkb** [hack-a-chain-software/indexer-kadena#88]
It's missing the "24h" on total volume. I guess it's 24h, but is it really it? @1Mateus 

![Image](https://github.com/user-attachments/assets/52d44d51-3d16-4994-8d3e-3507982668ce)

**Comment by bernardonery** [comment]
It looks like it's already done:


![Image](https://github.com/user-attachments/assets/21a1a14e-612c-4a9d-bbd0-04e85a9a2f3b)
