### ISSUE TITLE
[Test] Test new graphQL endpoint

### ISSUE THREAD

**Issue by rafaeldkb** [hack-a-chain-software/indexer-kadena#97]
Test API as a user

**Comment by rafaeldkb** [comment]
@mschead I'm trying to retrieve information from a transaction using a requestkey and it says it doesn't find the request key. 

**Query:**

query Transaction($requestKey: String!) {
  transaction(requestKey: $requestKey) {
    cmd {
      transactionId
      }
    }
  }
}

**Response**: 
"errors": [
    {
      "message": "Transfer with id 89nwsbqyqg9XwrTOnHWtAb-KTpdKTYg0Q5LTpLK5X7M not found",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "transaction"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Transfer with id 89nwsbqyqg9XwrTOnHWtAb-KTpdKTYg0Q5LTpLK5X7M not found",
            "    at TransactionDbRepository.getTransactionByRequestKey (/app/dist/kadena-server/repository/infra/repository/transaction-db-repository.js:147:19)",
            "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
            "    at async Object.transactionQueryResolver [as transaction] (/app/dist/kadena-server/resolvers/query/transaction-query-resolver.js:8:20)"
          ]
        }
      }
    }
  ],
  "data": {
    "transaction": null
  }
}

**Comment by rafaeldkb** [comment]
When I try to retrieve "Parent" from the block query it doesn't show any data option

query Block($hash: String!) {
  block(hash: $hash) {
    parent {
      
    }
  }
}

like, what should I add in the line below? i thought it was supposed to show some data options, and there's not really a variable

**Comment by rafaeldkb** [comment]
When I click to query the "payload" from the block query, this is what happens to the query:

query Block($hash: String!) {
  block(hash: $hash) {
    parent {
      parent {
        parent {
          parent {
            parent {
              parent {
                payloadHash
              }
            }
          }
        }
      }
    }
  }
}

This is when I click the "+" button for the payloadhash query, inside the block.

**Comment by rafaeldkb** [comment]
Making queries for total count of events inside blocks is returning 0 events, even though I know there were several transactions on the block (hash used: "Mm4o2NTaln9yEpZAIuMvbg-9yMuc3B49xwJgCiJv7Y8")

**Query**
query Block($hash: String!) {
  block(hash: $hash) {
    events {
      totalCount
    }
  }
  }
}

**Return**
{
  "data": {
    "block": {
      "events": {
        "totalCount": 0
      }
    }
  }
}

**Comment by rafaeldkb** [comment]
I don't really know what are the options to add for the variable "qualifiedEventName", and it seems its a requirement to query events, could you explain?

**Query**
query Events($qualifiedEventName: String!) {
  events(qualifiedEventName: **$qualifiedEventName**) {
    blockHash
  }
}

**Comment by rafaeldkb** [comment]
the query "CompletedBlockHeights" is returning null, with error. 

**Query**
query CompletedBlockHeights {
  completedBlockHeights {
    edges {
      node {
        chainId
      }
    }
  }
}

**Return**
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Query.completedBlockHeights.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "completedBlockHeights"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Query.completedBlockHeights.",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:559:13)",
            "    at resolveField (/app/node_modules/graphql/execution/execute.js:472:19)",
            "    at executeFields (/app/node_modules/graphql/execution/execute.js:292:18)",
            "    at executeOperation (/app/node_modules/graphql/execution/execute.js:236:122)",
            "    at executeImpl (/app/node_modules/graphql/execution/execute.js:116:14)",
            "    at execute (/app/node_modules/graphql/execution/execute.js:60:35)",
            "    at execute (/app/node_modules/apollo-server-core/dist/requestPipeline.js:207:48)",
            "    at processGraphQLRequest (/app/node_modules/apollo-server-core/dist/requestPipeline.js:150:34)",
            "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
            "    at async processHTTPRequest (/app/node_modules/apollo-server-core/dist/runHttpQuery.js:222:30)"
          ]
        }
      }
    }
  ],
  "data": null
}

**Comment by mschead** [comment]
> query Transactions($requestKey: String) { transactions(requestKey: $requestKey) { edges { node { id hash } } } }
> 
> **Response** { "data": { "transactions": { "edges": [] } } }

![Image](https://github.com/user-attachments/assets/cba66445-d86c-42a4-80ee-f7476999fc30)

**Comment by mschead** [comment]
Issue 3

![Image](https://github.com/user-attachments/assets/fe353bd9-eb44-4c5e-ab9a-7b9a5f578515)

**Comment by mschead** [comment]
Issue 4

![Image](https://github.com/user-attachments/assets/2fb4ec65-a411-4cf1-a94a-2378c52f5d46)

**Comment by mschead** [comment]
Issue 5

![Image](https://github.com/user-attachments/assets/bd8f2035-8fbd-46f9-832c-b8e5a113004c)

The parent is the block parent of the current block you're fetching. You should be able to get all the fields of a block, as you can see on this list. I'm not sure if you're using mac or windows, but if you click CMD + space or CTRL + space, the list will open.

**Comment by mschead** [comment]
Issue 6

I found that it was missing the implementation of the total count for transactions and events of a block. I will fix it. However, I did the query on the kadscan using the hash (Mm4o2NTaln9yEpZAIuMvbg-9yMuc3B49xwJgCiJv7Y8) you mentioned and it returned no results. 
I did on the database as well and I got the same thing.

![Image](https://github.com/user-attachments/assets/f6b181f5-2af1-418c-b1f8-568842557837)

**Comment by mschead** [comment]
Issue 7

It's the combination of module and name columns. An example is `coin.TRANSFER`.

![Image](https://github.com/user-attachments/assets/1f03d4de-c250-4300-8fd2-76a5bcbb5bd6)
![Image](https://github.com/user-attachments/assets/b90f8b7e-24a1-48d8-a7e0-d9755db4bd9a)

**Comment by mschead** [comment]
Issue 8

I will finish the completedBlockHeights query. This one is pending.
